### ISSUE TITLE
Generate rsyslog/nxlog compatible paersed log file per minute to get a near real time view ?

### ISSUE THREAD

**Issue by khurshid-alam** [molu8bits/modsecurity-parser#36]
Is it possible to generate rsyslog compatible log file with json format so that I can send that to any remote log server like kibana, graylog ?

On windows, log file can be handled through nxlog, On Linux (Ubuntu 22.04 ) rsyslog handles log file and can easily be forwared to graylog server.

The log file format can be json, for example, each log file seperated by blank line.

```json
{ "time": "15/Jan/2024:00:01:32 +0530", "transaction_id": "16573246656640753946", "remote_address": "152.32.153.53",
    "request": {
        "request_line": "GET / HTTP/1.1",
        "headers": {
            "Host": "192.168.5.99",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0"
        }
   }
    "response": "None",
    "audit_data": {
        "messages": [
            "Message: Warning. Pattern match \"^[\\\\d.:]+$\" at REQUEST_HEADERS:Host. [file \"C:\\/Program Files/ModSecurity IIS/owasp_crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf\"] [line \"810\"] [id \"920350\"] [rev \"2\"] [msg \"Host header is a numeric IP address\"] [data \"192.168.5.99\"] [severity \"WARNING\"] [ver \"OWASP_CRS/3.0.0\"] [maturity \"9\"] [accuracy \"9\"] [tag \"application-multi\"] [tag \"language-multi\"] [tag \"platform-multi\"] [tag \"attack-protocol\"] [tag \"OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST\"] [tag \"WASCTC/WASC-21\"] [tag \"OWASP_TOP_10/A7\"] [tag \"PCI/6.5.10\"]"]
    }
}

{ "time": "15/Jan/2024:00:01:35 +0530", "transaction_id": "16573246656640753979"}
```

**Comment by molu8bits** [comment]
Actually you can enable JSON format in modsecurity configuration.
modsecurity.conf example:

```
SecAuditLog /var/log/nginx/modsec_audit_json.log
SecAuditLogFormat JSON

```

**Comment by khurshid-alam** [comment]
We don't use nginx. We use it on windows server with IIS

**Comment by molu8bits** [comment]
Doesn't matter. modsecurity module for IIS should understand this line
`SecAuditLogFormat JSON`

**Comment by khurshid-alam** [comment]
@molu8bits 

Yes tried that before. Doesn't work. Logstash can't parse those.

```
[2024-01-20T15:29:47,005][ERROR][logstash.codecs.json     ][main][443d90abb733c7532a68914391b60
e=>"Unexpected character ('\\' (code 92)): was expecting double-quote to start field name\n at
```

All I want the output file to be json array. 

Currently we have this, each json dict seperated by a line break.

```json
{"transaction": 1, }
{"transaction: 2", }
```

I want this so that I can easily parse it.

```json
[
{"transaction": 1, },
{"transaction: 2", }
]
```

**Comment by molu8bits** [comment]
Logstash filter must be written to read and forward log entries. As far as I remember each line consists of a one single log entry so this should be processed - but everything depends on logstash configuration.

However few issues might be there:
1. Different versions of modsecurity can produce different output for audit log. There are small subtle differences but this might impact scenario when you want to build universal parser for logstash
2. Modsecurity doesn't always produce correct json format so it may happen that still some log entries won't be processed.
3. Even though output is supposed to be JSON still some fields are not. So you can't easily apply filters based on some fields. You can make graphs using "Host" or "User-Agent" but fields from "message" are very difficult to parse.

I don't know which logstash codec are you using but if this is default JSON - it may fail for due to one or more above points.


Long time ago I had some configuration to read Audit Log and process it using Promtail/Loki/Grafana stack to get realtime view. I was going to upload it to [https://github.com/molu8bits/loki-nginx-modsecurity](https://github.com/molu8bits/loki-nginx-modsecurity ) but never completed. If you are interested in such stack send me your anonymized raw log and I can check if it still works. Anyway still take into consideration above possible issues. You won't be able to get summary for e.g. rules id, get top attacks intercepted an so on.


Modsecurity-parser is not designed to process data flow to get realtime view and too much work is needed to transform it into such case. It's better to write custom processing module using Filebeat/Logstash/Fluentd/Promtail or anything like that. However due to many errors in Modsecurity it would be rather hard to do it. Some basic version for Filebeat you can find in mine another project (archived) [https://github.com/molu8bits/modsecurity-filebeat-kibana](https://github.com/molu8bits/modsecurity-filebeat-kibana).
